INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (1, "SVJ", "Lambo", 1000000, 1-20-2022, 2-20-2022);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (2, "GMC Denali", "Truck", 90000, 4-20-2022, 9-20-2022);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (3, "Code", "SQL", 1000, 5-6-2027, 3-23-2029);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (4, "Call of duty", "FPS", 500, 7-6-2012, 11-3-2028);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (5, "Bad Bunny", "Latin trap reggaeton", 100000000, 1-1-1994, 3-20-2022);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (6, "Lil Baby", "Rap", 300000, 4-3-1999, 6-18-2030);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (7, "I want to play soccer", "Soccer", 900000000, 7-9-1888, 10-18-2040);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (8, "Lets go for a jog", "Out Doors", 10, 2-1-2067, 2-3-2067);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (9, "I am short", "Genes", 90, 12-19-2003, 11-29-2019);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (10, "I am hungry", "Food", 800, 5-25-1782, 7-27-2777);

INSERT INTO users (id, name, age) VALUES (1, "Julio", 22);
INSERT INTO users (id, name, age) VALUES (2, "Gelly", 25);
INSERT INTO users (id, name, age) VALUES (3, "Alex", 15);
INSERT INTO users (id, name, age) VALUES (4, "Lupita", 20);
INSERT INTO users (id, name, age) VALUES (5, "Lenny", 15);
INSERT INTO users (id, name, age) VALUES (6, "Tita", 5);
INSERT INTO users (id, name, age) VALUES (7, "Chikis", 11);
INSERT INTO users (id, name, age) VALUES (8, "Tony", 14);
INSERT INTO users (id, name, age) VALUES (9, "Jay", 18);
INSERT INTO users (id, name, age) VALUES (10, "Jose", 24);
INSERT INTO users (id, name, age) VALUES (11, "Roger", 20);
INSERT INTO users (id, name, age) VALUES (12, "Antonio", 20);
INSERT INTO users (id, name, age) VALUES (13, "Marcus", 21);
INSERT INTO users (id, name, age) VALUES (14, "Blackie", 21);
INSERT INTO users (id, name, age) VALUES (15, "King", 50);
INSERT INTO users (id, name, age) VALUES (16, "Greg", 90);
INSERT INTO users (id, name, age) VALUES (17, "Drake", 41);
INSERT INTO users (id, name, age) VALUES (18, "Canelo", 71);
INSERT INTO users (id, name, age) VALUES (19, "Chapo", 96);
INSERT INTO users (id, name, age) VALUES (20, "Ronaldo", 47);

INSERT INTO pledges (id, amount, user_id, project_id) VALUES (1 );
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (4);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (5);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (6);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (7);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (8);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (9);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (10);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (11);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (12);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (13);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (14);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (15);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (16);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (17);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (18);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (19);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (20);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (21);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (22);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (23);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (24);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (25);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (26);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (27);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (28);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (29);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (30);